model:
  num_layers: 5
  hidden_channels: 576
  sg_emb_size: 128
  lat_hidden_channels: 284
  lat_num_layers: 1
  comp_num_layers: 2
  comp_hidden_channels: 128
  comp_phys_embeds:
    use: True
    z_emb_size: 128
    period_emb_size: 256
    group_emb_size: 16
    properties_proj_size: 64
    n_elements: 90
  sg_encoder:
    use: False # defaults to a simple Embedding(sg_emb_size) if this is False instead of SpaceGroupEncoder
    sg_yaml: /network/scratch/d/divya.sharma/crystals/data/crystallograpy/yaml
    symmetries_hiddens: [128, 16] # hidden layers of the symmetry vectors encoder
    symmetries_aggregation: "mean" # aggregation method for the symmetry vectors ; see SpaceGroupEncoder.aggregate_symmetry_embeddings
    space_group_size: 16 # embedding size of the space group's free embedding
    point_symmetry_size: 16 # embedding size of the space group's point symmetry's free embedding
    cl_system_size: 16 # embedding size of the space group's crystal lattice system's free embedding
  wyck_encoder:
    use: True
    wyck_embed_size: 64
optim:
  batch_size: 448
  lr: 0.0017
  epochs: 40
  es_patience: 7
  scheduler:
    name: "ReduceLROnPlateau"  # StepLR, ""
    patience: 4
    step_size: 5000
    decay_factor: 0.5